### ISSUE TITLE
[BUG] Crash when exec "tf show"

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [montblu/terrabutler#139]
```bash
$ terrabutler tf -site k8s show -json
Traceback (most recent call last):
  File "terrabutler/__main__.py", line 5, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1688, in invoke
  File "click/core.py", line 1688, in invoke
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "click/decorators.py", line 33, in new_func
  File "terrabutler/click.py", line 676, in tf_show_cli
  File "terrabutler/tf.py", line 100, in terraform_command_runner
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1883, in _execute_child
TypeError: expected str, bytes or os.PathLike object, not NoneType
[1098695] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by MiguelNdeCarvalho** [comment]
Fixed in #140
